Tibos.Admin/Areas/SYS/Controllers/DictController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Tibos.Common;
using Tibos.Domain;
using Tibos.Service.Contract;

namespace Tibos.Admin.Areas.SYS.Controllers
{
    [Area("SYS")]
    public class DictController : Controller
    {

        public DictIService _DictIService { get; set; }

        public DictTypeIService _DictTypeIService { get; set; }

        #region Dict
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Create(string Tid)
        {
            Dict model = new Dict();
            model.Tid = Tid;
            return View(model);
        }
        public IActionResult Edit(string Id)
        {
            var model = new Dict();
            if (!string.IsNullOrEmpty(Id))
            {
                model = _DictIService.Get(Id);
            }
            return View(model);
        }

        public IActionResult Detail()
        {
            return View();
        }

        [HttpPost]
        public JsonResult List(DictRequest request)
        {
            request.sortKey = "Sort";
            request.sortType = 0;
            IList<Dict> list = new List<Dict>();
            var count = 0;
            if (!string.IsNullOrEmpty(request.Tid))
            {
                 list = _DictIService.GetList(request);
                 count = _DictIService.GetCount(request);
            }
            Json reponse = new Json();
            reponse.code = 200;
            reponse.total = count;
            reponse.data = list;
            return Json(reponse);
        }


        [HttpPost]
        public JsonResult Create(Dict request)
        {
            request.Id = Guid.NewGuid().GuidTo16String();
            var id = _DictIService.Save(request);
            Json reponse = new Json();
            reponse.code = 200;
            reponse.status = 0;
            return Json(reponse);
        }

        [HttpPost]
        public JsonResult Edit(Dict request)
        {
            Json reponse = new Json();
            _DictIService.Update(request);
            reponse.code = 200;
            reponse.status = 0;
            return Json(reponse);
        }

        [HttpPost]
        public JsonResult EditStatus(string Id,int Status)
        {
            Json reponse = new Json();
            var model = _DictIService.Get(Id);
            if(model.Status != Status)
            {
                model.Status = Status;
                _DictIService.Update(model);
            }
            reponse.code = 200;
            reponse.status = 0;
            return Json(reponse);
        }

        [HttpPost]
        public JsonResult Del(string Id)
        {
            _DictIService.Delete(Id);
            Json reponse = new Json();
            reponse.code = 200;
            return Json(reponse);
        }

        #endregion

    }
}

Tibos.Admin/Components/SelectViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Tibos.Service.Contract;

namespace Tibos.Admin.Components
{
    public class SelectViewComponent:ViewComponent
    {


        public SelectViewComponent()
        {

        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View();
        }
    }
}

Tibos.Admin/Areas/SYS/Views/Dict/Create.cshtml
@{
    ViewData["Title"] = "创建";
    Layout = "/Views/Shared/_IFrame.cshtml";
}
@model Tibos.Domain.Dict
@Html.Partial("~/Areas/SYS/Views/Dict/_CreateOrEdit.cshtml",Model)

Tibos.Admin/Areas/SYS/Views/Dict/Edit.cshtml
@{
    ViewData["Title"] = "编辑";
    Layout = "/Views/Shared/_IFrame.cshtml";
}
@model Tibos.Domain.Dict
@Html.Partial("~/Areas/SYS/Views/Dict/_CreateOrEdit.cshtml", Model)

Tibos.Admin/Areas/SYS/Views/Dict/Index.cshtml
@{
    Layout = "/Views/Shared/_Layout.cshtml";
}

<body layadmin-themealias="default" style="">
    <div class="layui-fluid">
        <div class="layui-card">
            <div class="layui-form layui-card-header layuiadmin-card-header-auto">
                <div class="layui-form-item">
                    <div class="layui-inline">
                        <label class="layui-form-label">ID</label>
                        <div class="layui-input-block">
                            <input type="text" id="id" name="id" placeholder="请输入" autocomplete="off" class="layui-input">
                        </div>
                    </div>
                    <div class="layui-inline">
                        <label class="layui-form-label">用户名</label>
                        <div class="layui-input-block">
                            <input type="text" id="username" name="username" placeholder="请输入" autocomplete="off" class="layui-input">
                        </div>
                    </div>
                    <div class="layui-inline">
                        <label class="layui-form-label">邮箱</label>
                        <div class="layui-input-block">
                            <input type="text" id="email" name="email" placeholder="请输入" autocomplete="off" class="layui-input">
                        </div>
                    </div>
                    <div class="layui-inline">
                        <label class="layui-form-label">性别</label>
                        <div class="layui-input-block">
                            @await Component.InvokeAsync("Select")
                        </div>
                    </div>
                    <div class="layui-inline">
                        <button id="search" class="layui-btn" data-type="reload">
                            <i class="layui-icon layui-icon-search layuiadmin-button-btn"></i>
                        </button>
                    </div>
                </div>
            </div>

            <div class="layui-card-body">
                <div style="padding-bottom: 10px;">
                    <button class="layui-btn layuiadmin-btn-useradmin" data-type="batchdel">删除</button>
                    <button id="add" class="layui-btn layuiadmin-btn-useradmin" data-type="add">添加</button>
                </div>
                <table class="layui-hide" id="tableList" lay-filter="tableList"></table>
                <script>
                    layui.use('table', function () {
                        var table = layui.table;
                        table.render({
                            elem: '#tableList',
                            height: '600px'
                            , url: '/cms/news/list'
                            
                            ,request: {
                                pageName: 'pageIndex' //页码的参数名称，默认：page
                                , limitName: 'pageSize' //每页数据量的参数名，默认：limit
                            }
                            , response: {
                                statusName: 'status' //规定数据状态的字段名称，默认：code
                                , statusCode: 0 //规定成功的状态码，默认：0
                                , msgName: 'msg' //规定状态信息的字段名称，默认：msg
                                , countName: 'total' //规定数据总数的字段名称，默认：count
                                , dataName: 'data' //规定数据列表的字段名称，默认：data
                            }
                            , method: 'post'
                            , title: '用户数据表'
                            , cols: [[ //表头
                                { type: 'checkbox', fixed: 'left' },
                                {
                                    field: 'Id', title: 'ID', minWidth: 80, sort: true, fixed: 'left'
                                }
                                , { field: 'UserName', title: '用户名', minWidth: 80, fixed: 'left' }
                                , { field: 'Mobile', title: '手机号', minWidth: 80 }
                                , { field: 'Email', title: '邮箱', minWidth: 80 }
                                , { field: 'Status', title: '状态', minWidth: 177, sort: true }
                                , { field: 'Sex', title: '性别', minWidth: 177, sort: true }
                                , { field: 'LoginTime', title: '登录时间', minWidth: 80, sort: true }
                                , { field: 'LoginIp', title: '登录IP', minWidth: 80, sort: true }
                                , { title: '测试', minWidth: 80, templet: '#testTpl' }
                            ]]
                            , id: 'tableList'
                            , limit: 20
                            , limits: [20, 30, 40, 50, 60, 80, 100]
                            , page: true
                        });
                        //var $ = layui.$, active = {
                        //    reload: function () {
                        //        var username = $('#username');
                        //        var email = $('#email');
                        //        var sex = $('#sex');
                        //        //执行重载
                        //        table.reload('testReload', {
                        //            page: {
                        //                curr: 1 //重新从第 1 页开始
                        //            }
                        //            , where: {
                        //                key: {
                        //                    UserName: username.val(),
                        //                    Email: email.val(),
                        //                    Sex: sex.val()
                        //                }
                        //            }
                        //        });
                        //    }
                        //};
                        //自定义事件
                        $('#add').on('click', function () {
                            layer.open({
                                type: 2,
                                area: ['800px', '650px'],
                                fixed: false, //不固定
                                maxmin: true,
                                content: '/cms/news/create',
                                btn: ['确定', '取消'],
                                yes: function (index, layero) {
                                    $("#form").length;//直接获取表单长度=0
                                    $(layero).find("#form").length;//表单长度还是等于0
                                    var submit = layero.find('iframe').contents().find("#layuiadmin-app-form-submit");
                                    submit.click();

                                }

                            });
                        })

                        $('#search').on('click', function () {
                            var username = $('#username');
                            var email = $('#email');
                            var sex = $('#sex');
                            var id = $("#id");
                            //执行重载
                            table.reload('tableList', {
                                page: {
                                    curr: 1 //重新从第 1 页开始
                                }
                                , where: {
                                    Id: id.val(),
                                    UserName: username.val(),
                                    Email: email.val(),
                                    Sex: sex.val()
                                }
                            });
                            //var type = $(this).data('type');
                            //active[type] ? active[type].call(this) : '';
                        })

                        //监听表格排序问题
                        table.on('sort(tableList)', function (obj) { //注：tool是工具条事件名，tableList是table原始容器的属性 lay-filter="对应的值"
                            console.log(obj.field); //当前排序的字段名
                            console.log(obj.type); //当前排序类型：desc（降序）、asc（升序）、null（空对象，默认排序）
                            console.log(this); //当前排序的 th 对象

                            //尽管我们的 table 自带排序功能，但并没有请求服务端。
                            //有些时候，你可能需要根据当前排序的字段，重新向服务端发送请求，从而实现服务端排序，如：
                            table.reload('tableList', { //testTable是表格容器id
                                initSort: obj //记录初始排序，如果不设的话，将无法标记表头的排序状态。 layui 2.1.1 新增参数
                                , where: { //请求参数（注意：这里面的参数可任意定义，并非下面固定的格式）
                                    sortKey: obj.field //排序字段
                                    , sortType: obj.type == "desc" ? 1 : 0 //排序方式
                                }
                            });
                        });

                        //头工具栏事件
                        table.on('toolbar(tableList)', function (obj) {
                            var checkStatus = table.checkStatus(obj.config.id);
                            switch (obj.event) {
                                case 'getCheckData':
                                    var data = checkStatus.data;
                                    layer.alert(JSON.stringify(data));
                                    break;
                                case 'getCheckLength':
                                    var data = checkStatus.data;
                                    layer.msg('选中了：' + data.length + ' 个');
                                    break;
                                case 'isAll':
                                    layer.msg(checkStatus.isAll ? '全选' : '未全选');
                                    break;
                            };
                        });

                        //监听行工具事件
                        table.on('tool(tableList)', function (obj) {
                            var data = obj.data;
                            //console.log(obj)
                            if (obj.event === 'del') {
                                layer.confirm('真的删除行么', function (index) {
                                    obj.del();
                                    layer.close(index);
                                });
                            } else if (obj.event === 'edit') {
                                layer.prompt({
                                    formType: 2
                                    , value: data.email
                                }, function (value, index) {
                                    obj.update({
                                        email: value
                                    });
                                    layer.close(index);
                                });
                            }
                        });
                    });

                    function ValidateLog() {

                    }

                    //登录回调函数
                    function tips(data) {
                        alert(data);
                    }


                </script>

                <script type="text/html" id="testTpl">
                    {{#  if(d.Status % 2 === 0){ }}
                    <span style="color: #F581B1;">{{ d.UserName }}</span>
                    {{#  } else { }}
                    {{ d.UserName }}
                    {{#  } }}
                </script>

            </div>
        </div>
    </div>

    <div class="layui-layer-move" style="cursor: move; display: none;"></div>
</body>

Tibos.Admin/Areas/SYS/Views/Dict/_CreateOrEdit.cshtml
@model Tibos.Domain.Dict
<link href="~/css/font-awesome.min93e3.css" rel="stylesheet" />
<form id="form" class="layui-form" action="">
    <div class="layui-col-xs11" style="margin-top:5%">
        <div class="layui-form-item">
            @Html.HiddenFor(m => m.Id)
            @Html.HiddenFor(m => m.Tid)
            <label class="layui-form-label">名称</label>
            <div class="layui-input-block">
                <input type="text" name="Name" lay-verify="required" placeholder="请输入名称" autocomplete="off" class="layui-input" value="@Model?.Name">
            </div>
        </div>
        <div class="layui-form-item layui-form-text">
            <label class="layui-form-label">描述</label>
            <div class="layui-input-block">
                <textarea placeholder="请输入描述" name="Description" class="layui-textarea">@Model?.Description</textarea>
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">排序</label>
            <div class="layui-input-block">
                <input type="number" name="Sort" lay-verify="number" placeholder="请输入排序" autocomplete="off" class="layui-input" value="@Model?.Sort">
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">状态</label>
            <div class="layui-input-block">
                @{ 
                    var status = "";
                    if (Model?.Status == 1)
                    {
                        status = "checked=''";
                    }
                }
                <input type="checkbox" id="Status" name="Status" lay-skin="switch" lay-text="启用|关闭" title="是否启用" lay-filter="status" value="@Model?.Status" @status>
            </div>
        </div>
        <div class="layui-form-item layui-hide">
            <input type="button" lay-submit="" lay-filter="layuiadmin-app-form-submit" id="layuiadmin-app-form-submit" value="确认添加">
            <input type="button" lay-submit="" lay-filter="layuiadmin-app-form-edit" id="layuiadmin-app-form-edit" value="确认编辑">
        </div>

    </div>
</form>
<script>
    layui.use('form', function () {
        var form = layui.form;
        //自定义验证规则
        form.verify({

        });
        //监听开关
        form.on('switch(status)', function (data) {
            if (data.elem.checked) {
                $("#Status").val('1');
            } else {
                $("#Status").val('0');
            }
        });
        form.on('submit(layuiadmin-app-form-submit)', function (data) {
            var field = data.field; //获取提交的字段
            return postForm("/sys/dict/create", field, "add");
        });
        form.on('submit(layuiadmin-app-form-edit)', function (data) {
            var field = data.field; //获取提交的字段
            return postForm("/sys/dict/edit", field, "edit");
        });
        //提取公共提交表单方法
        function postForm(url, field, type) {
            var index = parent.layer.getFrameIndex(window.name); //先得到当前iframe层的索引
            //提交 Ajax 成功后，关闭当前弹层并重载表格
            var load = layer.load(1, {
                shade: [0.3, '#808080'] //0.1透明度的白色背景
            });
            $.post(url, field, function (data) {
                layer.close(load);
                if (data.code == 200) {
                    parent.layui.table.reload('tableList'); //重载表格
                    parent.layer.close(index); //再执行关闭
                    parent.layer.msg("操作成功!", {
                        time: 1000,
                        icon: 1,
                    });
                } else {
                    parent.layer.msg("操作失败!", {
                        time: 1000,
                        icon: 2,
                    });

                }
            })
        }
    });
</script>